[workspace]
members = [
    "./programs/amm-pool",
    "./programs/portfolio-program",
    "backend"
]
resolver = "2"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
panic = "abort"
overflow-checks = true  # ✅ required for Solana / Anchor

[profile.dev]
opt-level = 0

