# solana-defi-portfolio/programs/portfolio-program/Cargo.toml

[package]
name = "portfolio-program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.32.1"
anchor-spl = "0.32.1"
