# solana-defi-portfolio/programs/amm-pool/Cargo.toml

[package]
name = "amm-pool"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.32.1"
anchor-spl = "0.32.1"
