[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
amm_pool = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
portfolio_program = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[scripts]
test = "yarn run test"
build = "yarn run build"

[registry]
url = "https://anchor.projectserum.com"

[features]
seeds = false