# solana-defi-portfolio/programs/Cargo.toml

[workspace]
members = [
    "amm-pool",
    "portfolio-program"
]

# 🧠 Why:
# - Defines both programs as workspace members
# - Lets Anchor/Cargo build both together
# - Avoids the need for a separate root Cargo.toml
