[workspace]
members = [
    "programs/amm-pool",
    "programs/portfolio-program"
]
resolver = "2"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 0